apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeseries-simulation
  labels: 
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: forecastydevimages.azurecr.io/timeseries-simulation
          ports:
            - name: http
              containerPort: 8501
