apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: "#{REPOSITORY}#"

resources:
  - deployment.yaml
  - load-balancer.yaml

images:
  - name: forecastydevimages.azurecr.io/timeseries-simulation
    newTag: "#{Build.BuildId}#"

