apiVersion: v1
kind: Service
metadata:
  name: "#{REPOSITORY}#"
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: "#{Build.SourceBranchName}#-#{REPOSITORY}#"
spec:
  type: LoadBalancer
  ports:
    - name: traffic
      port: 80
      targetPort: http
  selector: 
    app: streamlit
