[datasets] # Toy datasets
[datasets.Retail]
name = "Retail sales"
url = "https://raw.githubusercontent.com/MaximeLutel/streamlit_prophet_datasets/main/retail_sales.csv"
date = "date"
target = "sales"
[datasets.House]
name = "House sales"
url = "https://raw.githubusercontent.com/MaximeLutel/streamlit_prophet_datasets/main/house_sales.csv"
date = "date"
target = "houses_sold"
[datasets.Energy]
name = "Energy consumption"
url = "https://raw.githubusercontent.com/MaximeLutel/streamlit_prophet_datasets/main/energy.csv"
date = "Date"
target = "Global_reactive_power"
[datasets.Weather]
name = "Weather"
url = "https://raw.githubusercontent.com/MaximeLutel/streamlit_prophet_datasets/main/weather.csv"
date = "datetime"
target = "temperature"
[datasets.Corn]
name = "Corn price"
url = "https://raw.githubusercontent.com/MaximeLutel/streamlit_prophet_datasets/main/corn_price.csv"
date = "week"
target = "corn_price"

[columns]
date = false # Name of date column, choose false to select it directly in the app.
target = false # Name of target column, choose false to select it directly in the app.
dimensions = false # List of dimension columns, choose false to select it directly in the app.
regressors = false # List of regressor columns, choose false to select it directly in the app.

[dataprep] # Default dataprep parameters
date_format = "%Y-%m-%d"
dimensions_agg = ["Mean", "Sum", "Min", "Max"] # List of possible target agg functions over dimensions. First is the default option.
remove_days = [] # List of days of week to remove from dataset.
# Select up to 6 elements among "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday".
remove_zeros = true # Whether or not to remove rows where target is 0 (true or false).
remove_negative = true # Whether or not to remove rows where target is <0 (true or false).
log_transform = false # Whether or not to apply a target log transform (true or false).

[model] # Default model parameters
seasonality_prior_scale = 10
holidays_prior_scale = 10
regressors_prior_scale = 10
changepoint_prior_scale = 0.05
growth = ['linear', 'logistic', 'flat'] # List of options, the first element of the list will be the default parameter.
cap = 5.0 # Cap value in case logistic growth is selected
floor = 0.0 # Floor value in case logistic growth is selected
seasonality_mode = ['additive', 'multiplicative'] # List of options, the first element of the list will be the default parameter.
changepoint_range = 0.8
holidays_country = "FR" # List of countries whose holidays will be added as regressors.
# Options: "FR", "US", "UK", "CA", "BR", "MX", "IN", "CN", "JP", "DE", "IT", "RU", "BE", "PT", "PL"
public_holidays = false
school_holidays = false
lockdown_events = []  # list of int with lockdown number (starting at 0) for the selected country

[horizon]
s = 86400 # Default number of seconds in validation set if dataset frequency is in seconds
H = 96 # Default number of hours in validation set if dataset frequency is in hours
D = 30 # Default number of days in validation set if dataset frequency is in days
W = 10 # Default number of weeks in validation set if dataset frequency is in weeks
M = 6 # Default number of months in validation set if dataset frequency is in months
Q = 4 # Default number of quarters in validation set if dataset frequency is in quarters
Y = 3 # Default number of years in validation set if dataset frequency is in years

[split]
CV = 5 # Default number of cross-validation folds if cross-validation is selected
gap_train_valid = 1 # Default number of days between training set and validation set

[validity]
min_data_points_train = 30 # Minimum number of datapoints (-1) to have in training set to train a model
min_data_points_val = 1 # Minimum number of datapoints (-1) to have in validation set to evaluate model
min_target_cardinality = 5 # Minimum number of distinct values that the target should have
max_cat_reg_cardinality = 5 # Maximum number of distinct values that a categorical regressor should have

[metrics]
[metrics.default] # List of metrics to display by default (among "MAPE", "RMSE", "SMAPE", "MAE", "MSE")
selection = ["MAPE", "RMSE", "SMAPE", "MAE"]
[metrics.digits] # Number of decimals to use when displaying metrics
MAPE = 4
SMAPE = 4
MSE = 1
RMSE = 2
MAE = 2

[style]
colors = ["#002244", "#ff0066", "#66cccc", "#ff9933", "#337788",
          "#429e79", "#474747", "#f7d126", "#ee5eab", "#b8b8b8"] # Color palette for visualizations
color_axis = '#d62728' # Color for axis on residuals chart and scatter plot
waterfall_digits = 2 # Number of digits in waterfall chart

[global]
seed = 42 # Random seed for modelling
