# It contains all the configs required in the project


names: ['Cathal Prendergast', 'Paul Moschella', 'Bret Mantone','Kaan Kaymak', 'Matthias Dohrn', 'Kate Silvestri',
              'Scott M Mizrahi', 'Scott M Mizrahi', 'Amanda Colyer', 'William Kaplowitz', 'James Gove', 'Vas Vergopoulos', 'Stephen Pender','Will Thomas','Toby Green','Matthew E Gidicsin','Pascal Ochs','Rahul Kalippurayil Moozhipurath','Erika Fonseca','Tuhin Mallick']

usernames: ['Cathal Prendergast', 'Paul Moschella', 'Bret Mantone','Kaan Kaymak', 'Matthias Dohrn', 'Kate Silvestri',
              'Scott M Mizrahi', 'Scott M Mizrahi', 'Amanda Colyer', 'William Kaplowitz', 'James Gove', 'Vas Vergopoulos', 'Stephen Pender','Will Thomas','Toby Green','Matthew E Gidicsin','Pascal Ochs','Rahul Kalippurayil Moozhipurath','Erika Fonseca','Tuhin Mallick']

passwords: ['EAu&j]%emnZjNq;', 
            '2E-=g6[%y[+da!;', 
            'CY#n,+(&Ftubi9Z',
            'hdVDRZT}&YL&8lh', 
            'IQuw!L1V(3{fJ(c',
            'w59wCS.&]9Pn7k[', 
            'Czt%&w}4K4cgqvQ', 
            'I0%HGc,J1gxE;aH', 
            'ZTkR#M8U;M-.#Yj', 
            'N_HffkOVUDp(4#@', 
            'C6j=b+,kUaq~u)J', 
            'dpWVy@e8QphT0+8',
            'Da6QGV{I.G)BR&e',
            'S]PKVt2%z,sCyQj',
            'hZ(gJfo%8-(@9%#',
            'JiU.O_)9qJA$T+j',
            'qVIWK=PL@&Rc.88',
            'mb)VV3o0lvlENxU',
            'InKfwOy_^+0G[oA']